# Generated by Django 3.1.4 on 2021-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Biography and Memoirs', max_length=50),
        ),
    ]
