# Generated by Django 3.1.4 on 2021-02-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descriptions',
            field=models.TextField(default='This is the amazing  book. You must read it.', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
