# Generated by Django 3.1.4 on 2021-02-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210222_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Mr.Dipesh Dulal', max_length=100),
        ),
    ]
