# Generated by Django 3.1.4 on 2021-02-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Logindata',
        ),
    ]
