# Generated by Django 3.1.4 on 2021-02-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210224_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logindata',
        ),
    ]
