# Generated by Django 3.1.4 on 2021-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_delete_logindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='quotes',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
        ),
    ]
