# Generated by Django 3.1.4 on 2021-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_aboutus_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='descriptions_page',
            field=models.TextField(default='This is the amazing  book. You must read it.'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='descriptions_person',
            field=models.TextField(default='People vary in terms of their physical appearance and personalities, and the words that are used to describe them are just as varied. Some words are better suited to describing the physical appearance of someone, some are best used to describe the person’s style, and others are ideal for describing the person’s character traits.'),
        ),
    ]
