# Generated by Django 3.1.4 on 2021-02-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210225_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/rukesh.shrestha.94651/', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='instragram',
            field=models.URLField(default='https://www.instagram.com/____rukesh____/', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/in/rukesh-shrestha-07914b1a3/', max_length=500),
        ),
    ]
